#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'mysql', "1.2.6"

cookbook 'rvm',
  :git => 'https://github.com/fnichol/chef-rvm',
  :ref => 'v0.9.0'

cookbook "chattin",
    :path => "vendor/cookbooks/chattin"

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
