#!/bin/bash
source "$( dirname "${BASH_SOURCE[0]}" )/lib/all.sh"
host=$1

# Usage: ./deploy.sh (SERVER|vagrant)
: ${1?"Usage: $0 HOSTNAME"}

host=$1

remote_bash "root@$host" '
  info "stopping unicorns"
  sudo god stop unicorns
  sleep 2

  info "kill any servivors"
  kill `ps aux | grep "unicorn master" | cut -d" " -f 2 `

  info "restarting god"
  sudo stop god
  sudo start god

  info "waiting 2 seconds for unicorns ..."
  sleep 2

  info "restarting nginx"
  sudo /etc/init.d/nginx restart
'
